# Generated by Django 4.2.7 on 2023-11-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("address", models.CharField(blank=True, default="", max_length=1024)),
                ("nip", models.CharField(blank=True, default="", max_length=13)),
                ("krs", models.CharField(blank=True, default="", max_length=10)),
                (
                    "capitalization",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndividualSavingsAccountOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.PositiveIntegerField()),
                (
                    "normal_interest_rate",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "special_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "special_interest_rate_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("date_start", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conditions", models.TextField(blank=True, default="")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_savings_account_offers",
                        to="finances.bank",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndividualDepositOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "normal_interest_rate",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "special_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("date_start", models.DateField()),
                ("maturity", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conditions", models.TextField(blank=True, default="")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_deposit_offers",
                        to="finances.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessSavingsAccountOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.PositiveIntegerField()),
                (
                    "normal_interest_rate",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "special_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "special_interest_rate_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("date_start", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conditions", models.TextField(blank=True, default="")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_savings_account_offers",
                        to="finances.bank",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessDepositOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "normal_interest_rate",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "special_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("date_start", models.DateField()),
                ("maturity", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conditions", models.TextField(blank=True, default="")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_deposit_offers",
                        to="finances.bank",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_bank_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="individualdepositoffer",
            constraint=models.CheckConstraint(
                check=models.Q(("maturity__gte", models.F("date_start"))),
                name="individual_maturity_gte_date_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessdepositoffer",
            constraint=models.CheckConstraint(
                check=models.Q(("maturity__gte", models.F("date_start"))),
                name="business_maturity_gte_date_start",
            ),
        ),
    ]
